### ISSUE TITLE
 cannot import name 'CLIPTextModelWithProjection' from 'transformers' by running python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 

### ISSUE THREAD

**Issue by KRIShark** [runwayml/stable-diffusion#43]
**I installd using** 
_conda env create -f environment.yaml
conda activate ldm_

The installation was successful. All the packages' ware installed.
**after it I started the command** 

_python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms_ 

**and got the error:**

`(ldm) K:\ImageAI\stable-diffusion>python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
Traceback (most recent call last):
  File "scripts/txt2img.py", line 21, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\__init__.py", line 38, in <module>
    from .models import (
  File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\__init__.py", line 20, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\autoencoder_asym_kl.py", line 21, in <module>
    from .autoencoder_kl import AutoencoderKLOutput
  File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\autoencoder_kl.py", line 21, in <module>
    from ..loaders import FromOriginalVAEMixin
  File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\loaders.py", line 45, in <module>
    from transformers import CLIPTextModel, CLIPTextModelWithProjection, PreTrainedModel, PreTrainedTokenizer
ImportError: cannot import name 'CLIPTextModelWithProjection' from 'transformers' (K:\anaconda\envs\ldm\lib\site-packages\transformers\__init__.py)`

**How to fix it?**

**Comment by CHNAICORP** [comment]
Upgrade your transformers version.
1. First, uninstall your transformers version

pip uninstall transformers

2. and than, upgrade your transformers version. 

pip install transformers==4.32.0

3. That's it

**Comment by CHNAICORP** [comment]
> **I installd using** _conda env create -f environment.yaml conda activate ldm_
> 
> The installation was successful. All the packages' ware installed. **after it I started the command**
> 
> _python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms_
> 
> **and got the error:**
> 
> `(ldm) K:\ImageAI\stable-diffusion>python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms Traceback (most recent call last): File "scripts/txt2img.py", line 21, in <module> from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\__init__.py", line 38, in <module> from .models import ( File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\__init__.py", line 20, in <module> from .autoencoder_asym_kl import AsymmetricAutoencoderKL File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\autoencoder_asym_kl.py", line 21, in <module> from .autoencoder_kl import AutoencoderKLOutput File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\models\autoencoder_kl.py", line 21, in <module> from ..loaders import FromOriginalVAEMixin File "K:\anaconda\envs\ldm\lib\site-packages\diffusers\loaders.py", line 45, in <module> from transformers import CLIPTextModel, CLIPTextModelWithProjection, PreTrainedModel, PreTrainedTokenizer ImportError: cannot import name 'CLIPTextModelWithProjection' from 'transformers' (K:\anaconda\envs\ldm\lib\site-packages\transformers\__init__.py)`
> 
> **How to fix it?**

Upgrade your transformers version
1. Uninstall your old transformers version
pip uninstall transformers 
2. And then. Upgrade transformers version to 4.32.0
pip install transformers==4.32.0
3. That's it.
