### ISSUE TITLE
Error running inpainting

### ISSUE THREAD

**Issue by TalTaiber** [runwayml/stable-diffusion#9]
Thank you for your great work!

I am having an issue with the inpaint pipeline. I get the following error:

`
Traceback (most recent call last):
File "/home/wonder/PycharmProjects/Dreambooth-Stable-Diffusion/test_runwayml.py", line 17, in <module>
    image = pipe(prompt=prompt, init_image=init_image, mask_image=mask_image).images[0]
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 371, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 290, in forward
    sample = self.conv_in(sample)
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
File "/home/wonder/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 4, 64, 64] to have 9 channels, but got 4 channels instead
`

I loaded my init_image and mask_image as PIL images and used the diffusers StableDiffusionInpaintPipeline, as shown in the example.
Does anyone know what I'm doing wrong?

**Comment by alexuvarovskyi** [comment]
Try to resize your image and mask so they would be divisible by 8. This helped me.

**Comment by TalTaiber** [comment]
> Try to resize your image and mask so they would be divisible by 8. This helped me.

Unfortunately, my images are already divisible by 8 (512*512). 
I also tried other images, to make sure the problem is not with the files. Still doesn't work.

**Comment by rmyj** [comment]
What model are you using?

**Comment by TalTaiber** [comment]
> 

`pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    revision="fp16",
    torch_dtype=torch.float16,
)`
as in the example

**Comment by TalTaiber** [comment]
> What model are you using?

`pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    revision="fp16",
    torch_dtype=torch.float16,
)`
as in the example

**Comment by alexuvarovskyi** [comment]
And how do you load your mask?

**Comment by TalTaiber** [comment]
> And how do you load your mask?

`from PIL import Image
init_image = Image.open("image_dir/image.jpg")
mask_image = Image.open("image_dir/mask.jpg")`

**Comment by alexuvarovskyi** [comment]
> 

Try this:
 `mask_image = Image.open("image_dir/mask.jpg",  'L')`
This loads your mask as grayscale.

**Comment by TalTaiber** [comment]
> > 
> 
> Try this: `mask_image = Image.open("image_dir/mask.jpg", 'L')` This loads your mask as grayscale.

Thanks for the idea, but this wasn't it.

Ultimately I reinstalled the vritual env and now it works.
